<table class="generic-table">
    <thead>
            <tr>
                <th>Quantité</th>
                <th>Produit</th>
                <th>Prix unitaire</th>
                <th>Prix total</th>
            </tr>
    </thead>
    <tbody>
        <?php foreach($basket as $item) { ?>
            <tr>
                <td><?php echo $item['quantity']; ?></td>
                <td><?php echo $item['name']; ?></td>
                <td><?php echo number_format($item['salePrice'],2 ,'.', ','); ?> €</td>
                <td><?php echo number_format(($item['salePrice']*$item['quantity']),2 ,'.' ,','); ?> €</td>
                <td><input id="<?php echo $item['mealId']; ?>" type="reset" class="button button-cancel small delete-meal"></td>
            </tr>
        <?php } ?>
    </tbody>
</table>