<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<aside class="notice">
    <?php $flash = new FlashBag();
            if($flash->hasMessages()){
                echo $message = $flash->fetchMessage();} ?>
</aside>
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php
        	// var_dump($requestUrl, $wwwUrl);
        	foreach ($meals as $meal) { ?>
        		<tr>
        	        <td><img src="<?php echo $wwwUrl ?>/images/meals/<?php echo $meal['Photo'] ?>"/></td>
        		    <td><?php echo $meal['Name'] ?>
                        <p><?php echo $meal['Description'] ?></p>
                    </td>
        	        <td><?php echo number_format($meal['SalePrice']) ?> €</td>
        	   </tr>
        	<?php } ?>
    </tbody>
</table>