<h2>Se connecter avec un compte utilisateur</h2>

<?php if(isset($error)){
    echo $error; } ?>


<form class="generic-form" method="POST">
    <fieldset>
        <legend>Information d'authentification</legend>
        <label>Email :
            <input type="email" name="email">
        </label>
        <label> Mot de passe :
            <input type="password" name="password">
        </label>
    </fieldset>

    <button class="button button-primary" type="submit">Créer un compte</button>
    <button class="button button-cancel" type="reset">Annuler</button>
</form>