<h2>Réservation d'une table</h2>

<form class="generic-form" method="POST">
    <fieldset>
        <legend>Informations</legend>
        <label>Date de réservation :
            <input type="date" name="orderDate">
            <input type="time" min="18:00" max="21:00" name="orderTime">
        </label>
        <label> Nombre de couverts :
            <input type="number" name="numberOfSeats">
        </label>
    </fieldset>

    <button class="button button-primary" type="submit">Réserver</button>
    <button class="button button-cancel" type="reset">Annuler</button>
</form>