<h2>Passer une commande</h2>

<form class="generic-form">
<input type="hidden" name="salePrice">
    <fieldset>
        <legend>Ajouter un article</legend>
        <label>Nom :
            <select id="meal">
            <?php foreach ($meals as $meal) : ?>
                <option value="<?php echo $meal['Id'] ?>"><?php echo $meal['Name'] ?></option>
            <?php endforeach; ?>
            </select>
            <article id="meal-details" class="meal-details no-left-label">
                    <img src="" alt="Photo du produit">
                    <p></p>
                    <span>Prix : <strong></strong></span>
            </article>
        </label>
        <label> Quantité :
            <input type="number" name="quantity">
        </label>
        <button id="validate-order" class="button button-primary">Ajouter</button>
    </fieldset>
<fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-summary"></section>
</fieldset>

    <button id="validate-order" class="button button-primary" disabled>Valider la commande</button>
    <button class="button button-cancel" type="reset">Annuler</button>
</form>

<script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>